# Generated by Django 3.1.1 on 2020-09-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodocityAPI', '0002_auto_20200927_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(default='https://marketplace.canva.com/EADzkaU9XJI/1/0/400w/canva-red-yellow-black-white-wavy-female-woman-girl-teen-portrait-simplified-illustration-square-laptop-sticker-_czOVX8ezRU.jpg'),
        ),
    ]
