# Generated by Django 3.1.1 on 2020-09-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodocityAPI', '0003_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='picture',
            field=models.URLField(default='https://marketplace.canva.com/EADzkaU9XJI/1/0/400w/canva-red-yellow-black-white-wavy-female-woman-girl-teen-portrait-simplified-illustration-square-laptop-sticker-_czOVX8ezRU.jpg'),
        ),
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.URLField(default='https://marketplace.canva.com/EADzkaU9XJI/1/0/400w/canva-red-yellow-black-white-wavy-female-woman-girl-teen-portrait-simplified-illustration-square-laptop-sticker-_czOVX8ezRU.jpg'),
        ),
    ]
